spring.application.name=archive-wizard
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql:${dbHost}:${dbPort}/${dbName}
spring.datasource.username=${dbUsername}
spring.datasource.password=${dbPassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE