### App Settings ###
spring.application.name=archive-wizard

### Database Credentials ###
spring.datasource.url=jdbc:postgresql://${dbHost}:${dbPort}/${dbName}
spring.datasource.username=${dbUsername}
spring.datasource.password=${dbPassword}

### JPA Settings ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

### Logging Settings ####
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

### Debugging Toggle ###
debug=true

### RSA Keys ###
rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem